"""Init async tables

Revision ID: 2381b61d3b24
Revises: 
Create Date: 2026-05-20 00:50:01.401461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2381b61d3b24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_contratos_mentee'), table_name='contratos_mentoria')
    op.drop_index(op.f('idx_contratos_paquete'), table_name='contratos_mentoria')
    op.drop_index(op.f('idx_mensajes_historial'), table_name='mensajes_chat')
    op.add_column('mentor_habilidades', sa.Column('id_mentor_habilidad', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('mentor_habilidades', sa.Column('nivel', sa.String(length=50), nullable=False))
    op.alter_column('mentor_habilidades', 'anios_experiencia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('_mentor_habilidad_uc', 'mentor_habilidades', ['id_mentor', 'id_habilidad'])
    op.drop_column('mentor_habilidades', 'nivel_dominio')
    op.drop_index(op.f('idx_paquetes_mentor'), table_name='paquetes_mentor')
    op.add_column('perfil_mentee', sa.Column('foto_perfil', sa.String(length=500), nullable=True))
    op.add_column('perfil_mentor', sa.Column('foto_perfil', sa.String(length=500), nullable=True))
    op.drop_constraint(op.f('salas_chat_id_mentee_id_mentor_key'), 'salas_chat', type_='unique')
    op.drop_index(op.f('idx_sesiones_fechas'), table_name='sesiones')
    op.drop_index(op.f('idx_usuarios_email'), table_name='usuarios')
    op.drop_constraint(op.f('usuarios_email_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_email_key'), 'usuarios', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_usuarios_email'), 'usuarios', ['email'], unique=False)
    op.create_index(op.f('idx_sesiones_fechas'), 'sesiones', ['fecha_hora_inicio_utc', 'fecha_hora_fin_utc'], unique=False)
    op.create_unique_constraint(op.f('salas_chat_id_mentee_id_mentor_key'), 'salas_chat', ['id_mentee', 'id_mentor'], postgresql_nulls_not_distinct=False)
    op.drop_column('perfil_mentor', 'foto_perfil')
    op.drop_column('perfil_mentee', 'foto_perfil')
    op.create_index(op.f('idx_paquetes_mentor'), 'paquetes_mentor', ['id_mentor'], unique=False)
    op.add_column('mentor_habilidades', sa.Column('nivel_dominio', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint('_mentor_habilidad_uc', 'mentor_habilidades', type_='unique')
    op.alter_column('mentor_habilidades', 'anios_experiencia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('mentor_habilidades', 'nivel')
    op.drop_column('mentor_habilidades', 'id_mentor_habilidad')
    op.create_index(op.f('idx_mensajes_historial'), 'mensajes_chat', ['id_sala', sa.literal_column('fecha_envio DESC')], unique=False)
    op.create_index(op.f('idx_contratos_paquete'), 'contratos_mentoria', ['id_paquete'], unique=False)
    op.create_index(op.f('idx_contratos_mentee'), 'contratos_mentoria', ['id_mentee'], unique=False)
    # ### end Alembic commands ###
