"""add_zona_horaria_preferida

Revision ID: c693bf9fc744
Revises: 88d3bbb566e8
Create Date: 2026-06-11 15:20:20.146720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c693bf9fc744'
down_revision: Union[str, Sequence[str], None] = '88d3bbb566e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil_mentor', sa.Column('zona_horaria_preferida', sa.String(length=50), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil_mentor', 'zona_horaria_preferida')
    # ### end Alembic commands ###
